# Test Distances

This notebook tests and gathers statistics on our distance functions, and verifies geometric properties.

* $y = \mathrm{mutation}(x)$ should be in a ball around $x$ of radius $r$, ie $d(x, y) \le r$.
* $z = \mathrm{crossover}(x, y)$ should be intermediate to $x$ and $y$, ie $d(x, z) + d(y, z) = d(x, y)$

We seek to verify these properties:

* Where $x$, $y$ and $z$ are *distributions* (with values), which are the individual elements (genes) of the trace representation (genome).
* Where $x$, $y$ and $z$ are actual *traces* (ie genomes). Mutation and crossover on traces are defined in terms of lower-level mutation and crossover on distributions.
* We can also look at distances at the phenotypic level.

We have three types of distribution:

* Coarse
* Fine
* Fine with repair

In reality, we expect geometric properties to hold *before repair only*. 

We have two types of trace (really, two types of *name* used in the trace):

* Linear
* Structured.

We have several different problems:

* Onemax
* Sphere
* Symbolic regression
* etc




In [1]:
import copy
import random
import numpy as np


# Properties of Distributions


In [2]:
def do_distances_dist(dist):
    """Given a Dist object, make "genes" (elements of the trace)
    x and y by sampling, and w by mutation and z by crossover. 
    
    Return a tuple of the interesting distances among these genes."""
    x = copy.deepcopy(dist)
    y = copy.deepcopy(dist)
    x.sample()
    y.sample()
    w = x.mutation()
    z = x.crossover(y)

    def d(x, y): return x.distance(y)

    return [
        d(x, y),
        d(x, w),
        d(y, w),
        d(x, z),
    ]

def stats_dist(dist, n_iters=100):
    """
    Given a Dist object, calculate the interesting distances
    for n_iters instances and return them in an array.
    """
    return np.array([
        do_distances_dist(dist)
        for i in range(n_iters)])


## Distribution properties - coarse distributions

In [3]:
from pto.core.base import Dist

# let's generate our stats for a few test Dists.
# these are coarse-grained Dists
dists = [
    Dist(random.random),
    Dist(random.randrange, 1, 4),
    Dist(random.choice, [0, 1])
]

for x in dists:
    print(stats_dist(x))
    

[[1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1.

## Distribution properties - fine distributions

In [4]:
from pto.core.fine_distributions import Random_cat, Random_int, Random_real

In [5]:
# now let's do the same, this time for some fine-grained Dists
dists = [
    Random_cat(random.choice, ['a', 'b', 'c']), # d.fun.__name__, d.seq
    Random_int(random.randint, 1, 5),           # d.fun.__name__, d.min, d.max, d.step
    Random_real(random.random, )                # d.fun.__name__, d.min, d.max, d.range
]

for x in dists:
    print(stats_dist(x))

[[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1.

# Distribution properties - repair distributions 

In [6]:
from pto.core.fine_distributions import Random_real_repair, Random_int_repair, Random_cat_repair
# now let's do the same, this time for some fine-grained Dists with repair
dists = [
    Random_cat_repair(random.choice, ['a', 'b', 'c']), # d.fun.__name__, d.seq
    Random_int_repair(random.randint, 1, 5),           # d.fun.__name__, d.min, d.max, d.step
    Random_real_repair(random.random, )                # d.fun.__name__, d.min, d.max, d.range
]

for x in dists:
    print(stats_dist(x))

[[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1.

# Trace properties

In [7]:
from pto import run

# import problem
from pto.problems import onemax, sphere, symbolic_regression

In [8]:
# some phenotype distances 

def hamming_distance(x, y):
    return sum(float(xi != yi) for xi, yi in zip(x, y))
def manhattan_distance(x, y):
    print(type(x[0]))
    x = np.array(x).astype(float)
    y = np.array(y).astype(float)
    return np.sum(x - y)
def tree_edit_distance(x, y):
    print("Not implemented") # TODO
    #print(x)
    #print(y)
    return 1

In [9]:
def do_distances(op, phenotype_distance):
    """Given an Op object, use it to sample individuals
    x and y, and create w by crossover and z by mutation.
    Then calculate the interesting distances among these
    individuals, again using Op. Calculate phenotypic 
    distances among them also."""

    # parents
    x = op.create_ind()
    y = op.create_ind()

    # child
    w = op.crossover_ind(x, y)

    # mutate a parent
    z = op.mutate_position_wise_ind(x)

    # we are interested in:
    # d(x, y): baseline distance between random pair
    # d(x, w) + d(y, w): crossover offspring distance should be <= d(x, y)?
    # d(x, z): mutation offspring distance should be "small"

    # phenotype distance also of interest, perhaps

    # do we worry about repair. the operators are geometric pre-repair

    def d(x, y): return op.distance_ind(x, y)
    def dp(x, y): return phenotype_distance(x.pheno, y.pheno)

    return [
        d(x, y),
        d(x, w),
        d(y, w),
        d(x, z),
        dp(x, y),
        dp(x, w),
        dp(y, w),
        dp(x, z)
    ]

def stats(op, phenotype_distance, n_iters=100):
    """
    Given an Op object (operators for a specific problem),
    calculate interesting distances many times.
    """
    return np.array([do_distances(op, phenotype_distance)
            for i in range(n_iters)])


In [12]:

onemax_coarse_lin_op = run(onemax.generator, onemax.fitness, Solver="search_operators", 
                gen_args=(onemax.size,), dist_type='coarse', name_type='lin')
onemax_fine_lin_op = run(onemax.generator, onemax.fitness, Solver="search_operators", 
                gen_args=(onemax.size,), dist_type='fine', name_type='lin')
onemax_repair_lin_op = run(onemax.generator, onemax.fitness, Solver="search_operators", 
                gen_args=(onemax.size,), dist_type='repair', name_type='lin')
onemax_repair_str_op = run(onemax.generator, onemax.fitness, Solver="search_operators", 
                gen_args=(onemax.size,), dist_type='repair', name_type='str')

sphere_op = run(sphere.generator, sphere.fitness, Solver="search_operators", 
                gen_args=(sphere.size,))
symbolic_regression_op = run(symbolic_regression.generator,
                             symbolic_regression.fitness, 
                             Solver="search_operators",
                             gen_args=(symbolic_regression.func_set, symbolic_regression.term_set), 
                             fit_args=(symbolic_regression.X_train, symbolic_regression.y_train))

ops = [onemax_coarse_lin_op, onemax_fine_lin_op, onemax_repair_lin_op, onemax_repair_str_op, sphere_op, symbolic_regression_op]
distances = (hamming_distance, manhattan_distance, tree_edit_distance)

for op, d in zip(ops, distances):
    print(stats(op, d))

[[5. 4. 1. 1. 5. 4. 1. 1.]
 [3. 2. 1. 0. 3. 2. 1. 0.]
 [2. 2. 0. 0. 2. 2. 0. 0.]
 [4. 3. 1. 1. 4. 3. 1. 1.]
 [7. 4. 3. 3. 7. 4. 3. 3.]
 [7. 5. 2. 0. 7. 5. 2. 0.]
 [6. 3. 3. 1. 6. 3. 3. 1.]
 [4. 3. 1. 1. 4. 3. 1. 1.]
 [4. 2. 2. 2. 4. 2. 2. 2.]
 [7. 4. 3. 2. 7. 4. 3. 2.]
 [4. 1. 3. 1. 4. 1. 3. 1.]
 [5. 2. 3. 0. 5. 2. 3. 0.]
 [4. 1. 3. 1. 4. 1. 3. 1.]
 [6. 2. 4. 1. 6. 2. 4. 1.]
 [4. 1. 3. 0. 4. 1. 3. 0.]
 [7. 5. 2. 0. 7. 5. 2. 0.]
 [4. 3. 1. 0. 4. 3. 1. 0.]
 [5. 3. 2. 0. 5. 3. 2. 0.]
 [6. 3. 3. 0. 6. 3. 3. 0.]
 [7. 3. 4. 0. 7. 3. 4. 0.]
 [2. 2. 0. 0. 2. 2. 0. 0.]
 [5. 4. 1. 1. 5. 4. 1. 1.]
 [8. 0. 8. 0. 8. 0. 8. 0.]
 [4. 0. 4. 1. 4. 0. 4. 1.]
 [3. 3. 0. 0. 3. 3. 0. 0.]
 [2. 0. 2. 0. 2. 0. 2. 0.]
 [6. 6. 0. 3. 6. 6. 0. 3.]
 [5. 2. 3. 1. 5. 2. 3. 1.]
 [4. 2. 2. 0. 4. 2. 2. 0.]
 [3. 1. 2. 0. 3. 1. 2. 0.]
 [4. 2. 2. 1. 4. 2. 2. 1.]
 [8. 3. 5. 0. 8. 3. 5. 0.]
 [5. 2. 3. 1. 5. 2. 3. 1.]
 [4. 2. 2. 1. 4. 2. 2. 1.]
 [7. 4. 3. 0. 7. 4. 3. 0.]
 [5. 3. 2. 1. 5. 3. 2. 1.]
 [1. 0. 1. 1. 1. 0. 1. 1.]
 